rpt.settings:
  type: config_object
  label: 'RPT settings'
  mapping:
    password_generate:
      type: boolean
      label: 'Generate password automatically'
    password_length:
      type: integer
      label: 'Generated password length'
